"use strict";
const TY_MODUL = 'modul';
const TY_VARIABLE = 'variable';
const TY_DEK_FUNGSI = 'dek-fungsi';
const TY_NAMA = 'nama';
const TY_PARAM = 'param';
const TY_ARG = 'arg';
const TY_STMT = 'stmt';
const TY_VALUE = 'value';
const TY_EXP = 'exp';
const STMT_VAR_ISI = 'var isi';
const STMT_VAR_ISI_BINOP = 'var isi binop';
const STMT_VAR_ISI_PANGGIL_FUNGSI = 'var isi panggil fungsi';
const STMT_PANGGIL_FUNGSI = 'panggil fungsi';
const ARG_VALUE = 'arg value';
const ARG_REF = 'arg var ref';
const ARG_REF_FUNGSI = 'arg fungsi ref';
