import { Point } from "./Point.js";
export declare class PFHelper {
    static readonly ATAS: number;
    static readonly KANAN: number;
    static readonly BAWAH: number;
    static readonly KIRI: number;
    static readonly KANAN_ATAS: number;
    static readonly KANAN_BAWAH: number;
    static readonly KIRI_ATAS: number;
    static readonly KIRI_BAWAH: number;
    private ruteJalan;
    private _cellWidth;
    private _cellHeight;
    private _langkahTotal;
    private _langkahIdx;
    private jalanIdx;
    private _pos;
    private posTemp;
    private _arah;
    private _updateArahCallBack;
    private _sedangJalan;
    constructor();
    reset(): void;
    start(data: Array<any>): void;
    private updateArah;
    private updatePos;
    update(): void;
    get cellWidth(): number;
    set cellWidth(value: number);
    get cellHeight(): number;
    set cellHeight(value: number);
    get langkahTotal(): number;
    set langkahTotal(value: number);
    get pos(): Point;
    set pos(value: Point);
    get sedangJalan(): Boolean;
    get arah(): number;
    set arah(value: number);
    get updateArahCallBack(): Function;
    set updateArahCallBack(value: Function);
}
